# Generated by Django 4.2.1 on 2023-06-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=256)),
                ('car_model', models.CharField(max_length=256)),
                ('car_id', models.CharField(max_length=256)),
            ],
        ),
    ]
